services:
  code-exec-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: code-exec-app
    ports:
      - '3000:3000'
    command: yarn dev
    depends_on:
      - mongo
    env_file:
      - .env.dev

  mongo:
    image: mongo
    container_name: code-exec-mongo
    ports:
      - '27017:27017'
